// 读取data.json文件提供完整的订阅源
import { readFileSync } from 'fs';
import { join } from 'path';

export default function handler(req, res) {
  try {
    // 读取data.json文件
    const dataPath = join(process.cwd(), 'data.json');
    const jsonData = JSON.parse(readFileSync(dataPath, 'utf8'));
    const apiSites = jsonData.api_site;

    // 生成M3U内容
    let m3uContent = "#EXTM3U\n";
    m3uContent += "# Generated by LunaTV\n";
    m3uContent += `# 更新时间: ${new Date().toLocaleString()}\n`;
    m3uContent += `# 资源数量: ${Object.keys(apiSites).length}\n\n`;
    
    for (const [key, site] of Object.entries(apiSites)) {
      const group = site.is_adult ? "成人资源" : "普通资源";
      m3uContent += `#EXTINF:-1 tvg-id="${key}" tvg-name="${site.name}" group-title="${group}",${site.name}\n`;
      m3uContent += `${site.api}\n\n`;
    }
    
    // 修正响应头 - 让浏览器和影视仓直接显示内容，不下载
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Content-Disposition', 'inline'); // 关键：内联显示，不下载
    
    res.send(m3uContent);
    
  } catch (error) {
    console.error('Error:', error);
    res.status(500).send('无法生成订阅源');
  }
}