export default function handler(req, res) {
  // 硬编码您的API数据（简化版，实际需要完整数据）
  const apiSites = {
    "1080zyku": {
      "api": "https://api.1080zyku.com/inc/api_mac10.php",
      "name": "TV-1080资源", 
      "is_adult": false
    },
    "155api": {
      "api": "https://155api.com/api.php/provide/vod",
      "name": "AV-155资源",
      "is_adult": true
    },
    "360zy": {
      "api": "https://360zy.com/api.php/provide/vod", 
      "name": "TV-360资源",
      "is_adult": false
    }
    // 这里需要把您data.json中的所有API站点都加进来
  };

  let m3uContent = "#EXTM3U\n";
  m3uContent += "# Generated by LunaTV\n\n";
  
  for (const [key, site] of Object.entries(apiSites)) {
    const group = site.is_adult ? "成人资源" : "普通资源";
    m3uContent += `#EXTINF:-1 group-title="${group}",${site.name}\n`;
    m3uContent += `${site.api}\n\n`;
  }
  
  res.setHeader('Content-Type', 'audio/x-mpegurl; charset=utf-8');
  res.setHeader('Cache-Control', 'no-cache');
  res.send(m3uContent);
}